name: my_verizon
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  email_validator_flutter: ^1.0.0
  email_validator: ^3.0.0
  url_launcher: ^6.3.1
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  assets:
    - images/verizon.png